### PR TITLE
Update jquery dependency

### LINKED ISSUE #37: No drop area on upload page
### Setup

- MW version: 1.35+
- SBU version: 1.6+

### Issue
 Originally reported [on mediawiki.org](https://www.mediawiki.org/wiki/Topic:Vvbr0a5ax1nwo06o)

"MW 1.35, SimpleBatchUpload 1.6

Symptoms: No drop area on upload page (just a file upload button), error on Chrome console stating jquery.ui.widget is deprecated

### Suggested fix
Fix: in src/SimpleBatchUpload.php, replace

`'dependencies' => [ 'jquery.ui.widget' ],`

with

`'dependencies' => [ 'jquery.ui' ],`

### PR DESCRIPTION
**Pull request by kghbln**
Fix as suggested by [Ti_infotrad]( https://www.mediawiki.org/wiki/User:Ti_infotrad)

Fixes #37

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw You will have to check if this actually fixes the issue (appears like it) and if this is backwards compatible (which I cannot assess)

**Comment by pastakhov** [comment]
+1 it works for me on 1.35

**Comment by JeroenDeDauw** [comment]
Might no longer work on older MW versions though. Can someone figure out if `jquery.ui` included the widget code on 1.31. My guess is that it did not. So that we need to raise MW requirements if we merge this.

**Comment by kghbln** [comment]
Looks like it. I asked [on phabricator](https://phabricator.wikimedia.org/T219604#6524186).

**Comment by kghbln** [comment]
I got an answer, but I am pretty sure my question was not understood correctly.

**Review by kizule — CHANGES_REQUESTED** [review]
Per [this](https://codesearch.wmcloud.org/search/?q=%5B%22%27%5Djquery%5C.(ui%5C.(core%7Ccore%5C.styles%7Caccordion%7Cautocomplete%7Cbutton%7Cdatepicker%7Cdialog%7Cdraggable%7Cdroppable%7Cmenu%7Cmouse%7Cposition%7Cprogressbar%7Cresizable%7Cselectable%7Cslider%7Csortable%7Ctabs%7Ctooltip%7Cwidget)%7Ceffects%5C.(core%7Cblind%7Cclip%7Cdrop%7Chighlight%7Cscale%7Cshake))%5B%22%27%5D&i=nope&files=&repos=ProfessionalWiki/SimpleBatchUpload), tests/phpunit/SimpleBatchUploadTest.php should be changed also.

**Review by thijskh — CHANGES_REQUESTED** [review]
I have tested the change in 1.31 and where the functionality was previously working, with this change it breaks. So probably it needs to check for >= 1.35.

**Comment by thijskh** [comment]
This fixes it, using a similar way of testing already used further down in the same file.

```diff
--- src/SimpleBatchUpload.php.orig	2020-12-29 13:20:48.799088563 +0100
+++ src/SimpleBatchUpload.php	2020-12-29 15:48:35.929435038 +0100
@@ -97,6 +97,12 @@
 	}
 
 	protected function getUploadSupportModuleDefinition(): array {
+		if ( version_compare( $GLOBALS[ 'wgVersion' ], '1.35.0', '>' ) ) {
+			$dependencies = [ 'jquery.ui' ];
+		} else {
+			$dependencies = [ 'jquery.ui.widget' ];
+		}
+
 		return [ 'ext.SimpleBatchUpload.jquery-file-upload' =>
 
 			$this->getBasePathsForNonComposerModules() +
@@ -105,7 +111,7 @@
 				'scripts' => [ 'res/jquery.fileupload.js' ],
 				'styles' => [ 'res/jquery.fileupload.css' ],
 				'position' => 'top',
-				'dependencies' => [ 'jquery.ui.widget' ],
+				'dependencies' => $dependencies,
 			],
 		];
 	}
```

**Comment by thijskh** [comment]
@JeroenDeDauw Thanks for merging my PR, have you seen my patch in the last comment in this one? Running for months now with this in production.

**Comment by JeroenDeDauw** [comment]
PR welcome

**Comment by thijskh** [comment]
This can now be closed as it has been fixed in #40

**Pull request closed without merging**
