### PR TITLE
WIP: Rename uploaded files

### PR DESCRIPTION
**Pull request by ankostis**
As explained in the [discussion page](https://www.mediawiki.org/wiki/Topic:Um1qxu4dgnwyr5fy) this is an attempt to add a new "special" paramater `+rename`  to `{{#batchupload:...}}` function that specifies a regular-expression used to rename uploaded files.

The branch contains also outdated commits that can be squashed and re-written, if this PR is deemed worthy for merging.  Also no documentation is provided, and don't know how to craft testcases.
Hence, the `WIP` in the title.

### CODE REVIEW

**Comment by revansx** [comment]
Is there any progress on getting this feature added to the main extension project?

**Comment by revansx** [comment]
Is there any progress on getting this feature added to the main extension project?

**Comment by ankostis** [comment]
None that i'm ware of.

**Comment by JeroenDeDauw** [comment]
Hi. New maintainer here. Did you test the code changes manually? Did/do you use them on any wiki?

**Comment by ankostis** [comment]
If you ask me, yes, they are in production for a 2 years now, and nobody complained.

**Comment by JeroenDeDauw** [comment]
Can I see this on a public wiki?

**Comment by ankostis** [comment]
Unfortunately, will remain for ever private :-(

**Comment by JeroenDeDauw** [comment]
Seeing this in action would increase my confidence that we can safely merge this.

**Comment by JeroenDeDauw** [comment]
I'll try it on my own wiki soon

**Comment by revansx** [comment]
I will have a site set-up soon for EMWCon 2020 that uses this repo. User's
will be able to create accounts that I will approve. My work being
presented this year is based on this branch of the extension.

[1]  https://www.mediawiki.org/wiki/EMWCon_Spring_2020

**Comment by revansx** [comment]
actually, my work is based on ankostis's repo:

https://github.com/ankostis/SimpleBatchUpload/tree/rename-files

**Comment by JeroenDeDauw** [comment]
Would be fantastic if you could update the docs in the README file.

**Pull request merged**
